inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'project_files/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
