# frozen_string_literal: true

# Opal doesn't support Ruby autoload. This file explicitly requires
# all Moxml modules that would normally be lazy-loaded via autoload
# in lib/moxml.rb. Loaded by the Opal Rakefile before spec_helper.

require "moxml/version"
require "moxml/error"
require "moxml/native_attachment"
require "moxml/native_attachment/opal"
require "moxml/xml_utils"
require "moxml/xml_utils/encoder"
require "moxml/node"
require "moxml/node_set"
require "moxml/document"
require "moxml/element"
require "moxml/attribute"
require "moxml/text"
require "moxml/cdata"
require "moxml/comment"
require "moxml/processing_instruction"
require "moxml/declaration"
require "moxml/namespace"
require "moxml/doctype"
require "moxml/entity_reference"
require "moxml/entity_registry"
require "moxml/entity"
require "moxml/entity/restorer"
require "moxml/entity/reference"
require "moxml/xml_emitter"
require "moxml/adapter"
require "moxml/adapter/base"
require "moxml/adapter/customized_rexml"
require "moxml/adapter/customized_rexml/entity_reference"
require "moxml/adapter/customized_rexml/formatter"
require "moxml/sax"
require "moxml/sax/handler"
require "moxml/sax/element_handler"
require "moxml/sax/block_handler"
require "moxml/sax/namespace_splitter"
require "moxml/adapter/rexml"
require "moxml/adapter/customized_oga"
require "moxml/adapter/customized_oga/entity_decoder"
require "moxml/adapter/customized_oga/raw_value_override"
require "moxml/adapter/customized_oga/xml_declaration"
require "moxml/adapter/customized_oga/xml_generator"
require "moxml/adapter/oga"
require "moxml/builder"
require "moxml/context"
require "moxml/config"
require "moxml/xpath"
require "moxml/xpath/engine"
require "moxml/xpath/context"
require "moxml/xpath/conversion"
require "moxml/xpath/cache"
require "moxml/xpath/lexer"
require "moxml/xpath/parser"
require "moxml/xpath/compiler"
require "moxml/xpath/errors"
require "moxml/xpath/ast/node"
require "moxml/xpath/ruby/node"
require "moxml/xpath/ruby/generator"
