name: opal

on:
  push:
    branches: [main]
    tags: [ v* ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Opal dependencies
        run: |
          npm list -g opal-compiler || npm install -g opal-compiler
          bundle exec rake opal:generate_entity_data

      - name: Run Opal tests
        run: bundle exec rake spec:opal
